# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ze-code-challenge.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(929, 728)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(929, 728))
        MainWindow.setFocusPolicy(QtCore.Qt.NoFocus)
        MainWindow.setAcceptDrops(True)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setDocumentMode(True)
        MainWindow.setDockNestingEnabled(False)
        MainWindow.setDockOptions(QtWidgets.QMainWindow.AllowTabbedDocks|QtWidgets.QMainWindow.AnimatedDocks)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tabWidget.setElideMode(QtCore.Qt.ElideMiddle)
        self.tabWidget.setDocumentMode(True)
        self.tabWidget.setMovable(True)
        self.tabWidget.setTabBarAutoHide(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tabHome = QtWidgets.QWidget()
        self.tabHome.setObjectName("tabHome")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tabHome)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.splitter_5 = QtWidgets.QSplitter(self.tabHome)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter_5.sizePolicy().hasHeightForWidth())
        self.splitter_5.setSizePolicy(sizePolicy)
        self.splitter_5.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_5.setObjectName("splitter_5")
        self.groupBox = QtWidgets.QGroupBox(self.splitter_5)
        self.groupBox.setCheckable(True)
        self.groupBox.setObjectName("groupBox")
        self.formLayout_2 = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout_2.setObjectName("formLayout_2")
        self.splitter_4 = QtWidgets.QSplitter(self.groupBox)
        self.splitter_4.setOrientation(QtCore.Qt.Vertical)
        self.splitter_4.setObjectName("splitter_4")
        self.label = QtWidgets.QLabel(self.splitter_4)
        self.label.setObjectName("label")
        self.lineEditIdPartner = QtWidgets.QLineEdit(self.splitter_4)
        self.lineEditIdPartner.setStyleSheet("padding: 5px 5px;\n"
" \n"
"  border: 2px solid #ccc;\n"
"  border-radius: 4px;\n"
"  background-color: #f8f8f8;")
        self.lineEditIdPartner.setClearButtonEnabled(True)
        self.lineEditIdPartner.setObjectName("lineEditIdPartner")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.splitter_4)
        self.pushButtonSearchById = QtWidgets.QPushButton(self.groupBox)
        self.pushButtonSearchById.setObjectName("pushButtonSearchById")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.pushButtonSearchById)
        self.groupBox_2 = QtWidgets.QGroupBox(self.splitter_5)
        self.groupBox_2.setCheckable(True)
        self.groupBox_2.setObjectName("groupBox_2")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox_2)
        self.formLayout.setObjectName("formLayout")
        self.pushButtonSearchByCoordinates = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButtonSearchByCoordinates.setObjectName("pushButtonSearchByCoordinates")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.pushButtonSearchByCoordinates)
        self.splitter_3 = QtWidgets.QSplitter(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter_3.sizePolicy().hasHeightForWidth())
        self.splitter_3.setSizePolicy(sizePolicy)
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setObjectName("splitter_3")
        self.splitter_2 = QtWidgets.QSplitter(self.splitter_3)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.label_2 = QtWidgets.QLabel(self.splitter_2)
        self.label_2.setObjectName("label_2")
        self.lineEditLatitude = QtWidgets.QLineEdit(self.splitter_2)
        self.lineEditLatitude.setStyleSheet("padding: 5px 5px;\n"
"  \n"
"  border: 2px solid #ccc;\n"
"  border-radius: 4px;\n"
"  background-color: #f8f8f8;")
        self.lineEditLatitude.setClearButtonEnabled(True)
        self.lineEditLatitude.setObjectName("lineEditLatitude")
        self.splitter = QtWidgets.QSplitter(self.splitter_3)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.label_3 = QtWidgets.QLabel(self.splitter)
        self.label_3.setObjectName("label_3")
        self.lineEditLongitude = QtWidgets.QLineEdit(self.splitter)
        self.lineEditLongitude.setStyleSheet("padding: 5px 5px;\n"
"  \n"
"  border: 2px solid #ccc;\n"
"  border-radius: 4px;\n"
"  background-color: #f8f8f8;")
        self.lineEditLongitude.setClearButtonEnabled(True)
        self.lineEditLongitude.setObjectName("lineEditLongitude")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.splitter_3)
        self.gridLayout_2.addWidget(self.splitter_5, 0, 0, 1, 1)
        self.widget = QtWebEngineWidgets.QWebEngineView(self.tabHome)
        self.widget.setObjectName("widget")
        self.gridLayout_2.addWidget(self.widget, 1, 0, 1, 1)
        self.textEdit = QtWidgets.QTextEdit(self.tabHome)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit.sizePolicy().hasHeightForWidth())
        self.textEdit.setSizePolicy(sizePolicy)
        self.textEdit.setMinimumSize(QtCore.QSize(331, 511))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.textEdit.setFont(font)
        self.textEdit.setStyleSheet("width: 100%;\n"
"  height: 150px;\n"
"  padding: 12px 20px;\n"
"  \n"
"  border: 2px solid #ccc;\n"
"  border-radius: 4px;\n"
"  background-color: #f8f8f8;\n"
"  ")
        self.textEdit.setAutoFormatting(QtWidgets.QTextEdit.AutoAll)
        self.textEdit.setReadOnly(False)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout_2.addWidget(self.textEdit, 1, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.tabHome)
        font = QtGui.QFont()
        font.setFamily("KacstBook")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 0, 1, 1, 1)
        self.tabWidget.addTab(self.tabHome, "")
        self.tabCreate = QtWidgets.QWidget()
        self.tabCreate.setObjectName("tabCreate")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tabCreate)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.splitter_6 = QtWidgets.QSplitter(self.tabCreate)
        self.splitter_6.setOrientation(QtCore.Qt.Vertical)
        self.splitter_6.setObjectName("splitter_6")
        self.label_5 = QtWidgets.QLabel(self.splitter_6)
        self.label_5.setObjectName("label_5")
        self.lineEditTradingName = QtWidgets.QLineEdit(self.splitter_6)
        self.lineEditTradingName.setStyleSheet("padding: 5px 5px;\n"
"  \n"
"  border: 2px solid #ccc;\n"
"  border-radius: 4px;\n"
"  background-color: #f8f8f8;")
        self.lineEditTradingName.setObjectName("lineEditTradingName")
        self.gridLayout_5.addWidget(self.splitter_6, 2, 0, 1, 1)
        self.splitter_7 = QtWidgets.QSplitter(self.tabCreate)
        self.splitter_7.setOrientation(QtCore.Qt.Vertical)
        self.splitter_7.setObjectName("splitter_7")
        self.label_6 = QtWidgets.QLabel(self.splitter_7)
        self.label_6.setObjectName("label_6")
        self.lineEditOwnerName = QtWidgets.QLineEdit(self.splitter_7)
        self.lineEditOwnerName.setStyleSheet("padding: 5px 5px;\n"
"  \n"
"  border: 2px solid #ccc;\n"
"  border-radius: 4px;\n"
"  background-color: #f8f8f8;")
        self.lineEditOwnerName.setObjectName("lineEditOwnerName")
        self.gridLayout_5.addWidget(self.splitter_7, 3, 0, 1, 1)
        self.splitter_8 = QtWidgets.QSplitter(self.tabCreate)
        self.splitter_8.setOrientation(QtCore.Qt.Vertical)
        self.splitter_8.setObjectName("splitter_8")
        self.label_7 = QtWidgets.QLabel(self.splitter_8)
        self.label_7.setObjectName("label_7")
        self.lineEditDocument = QtWidgets.QLineEdit(self.splitter_8)
        self.lineEditDocument.setStyleSheet("padding: 5px 5px;\n"
" \n"
"  border: 2px solid #ccc;\n"
"  border-radius: 4px;\n"
"  background-color: #f8f8f8;")
        self.lineEditDocument.setMaxLength(18)
        self.lineEditDocument.setObjectName("lineEditDocument")
        self.gridLayout_5.addWidget(self.splitter_8, 4, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.tabCreate)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.splitter_9 = QtWidgets.QSplitter(self.groupBox_3)
        self.splitter_9.setOrientation(QtCore.Qt.Vertical)
        self.splitter_9.setObjectName("splitter_9")
        self.label_8 = QtWidgets.QLabel(self.splitter_9)
        self.label_8.setObjectName("label_8")
        self.textEditCoverageArea = QtWidgets.QTextEdit(self.splitter_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEditCoverageArea.sizePolicy().hasHeightForWidth())
        self.textEditCoverageArea.setSizePolicy(sizePolicy)
        self.textEditCoverageArea.setStyleSheet("width: 100%;\n"
"  height: 150px;\n"
"  padding: 12px 20px;\n"
"  \n"
"  border: 2px solid #ccc;\n"
"  border-radius: 4px;\n"
"  background-color: #f8f8f8;\n"
"  ")
        self.textEditCoverageArea.setDocumentTitle("")
        self.textEditCoverageArea.setObjectName("textEditCoverageArea")
        self.gridLayout_3.addWidget(self.splitter_9, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox_3, 5, 0, 1, 2)
        self.groupBox_4 = QtWidgets.QGroupBox(self.tabCreate)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.splitter_10 = QtWidgets.QSplitter(self.groupBox_4)
        self.splitter_10.setOrientation(QtCore.Qt.Vertical)
        self.splitter_10.setObjectName("splitter_10")
        self.label_9 = QtWidgets.QLabel(self.splitter_10)
        self.label_9.setObjectName("label_9")
        self.lineEditLatitude_2 = QtWidgets.QLineEdit(self.splitter_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditLatitude_2.sizePolicy().hasHeightForWidth())
        self.lineEditLatitude_2.setSizePolicy(sizePolicy)
        self.lineEditLatitude_2.setStyleSheet("padding: 5px 5px;\n"
" \n"
"  border: 2px solid #ccc;\n"
"  border-radius: 4px;\n"
"  background-color: #f8f8f8;")
        self.lineEditLatitude_2.setClearButtonEnabled(True)
        self.lineEditLatitude_2.setObjectName("lineEditLatitude_2")
        self.gridLayout_4.addWidget(self.splitter_10, 0, 0, 1, 1)
        self.splitter_12 = QtWidgets.QSplitter(self.groupBox_4)
        self.splitter_12.setOrientation(QtCore.Qt.Vertical)
        self.splitter_12.setObjectName("splitter_12")
        self.label_10 = QtWidgets.QLabel(self.splitter_12)
        self.label_10.setObjectName("label_10")
        self.lineEditLongitude_2 = QtWidgets.QLineEdit(self.splitter_12)
        self.lineEditLongitude_2.setStyleSheet("padding: 5px 5px;\n"
"  \n"
"  border: 2px solid #ccc;\n"
"  border-radius: 4px;\n"
"  background-color: #f8f8f8;")
        self.lineEditLongitude_2.setClearButtonEnabled(True)
        self.lineEditLongitude_2.setObjectName("lineEditLongitude_2")
        self.gridLayout_4.addWidget(self.splitter_12, 0, 1, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox_4, 6, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem, 9, 1, 1, 1)
        self.pushButtonSaveEntry = QtWidgets.QPushButton(self.tabCreate)
        self.pushButtonSaveEntry.setObjectName("pushButtonSaveEntry")
        self.gridLayout_5.addWidget(self.pushButtonSaveEntry, 8, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem1, 8, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem2, 8, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 43, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem3, 7, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.tabCreate)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.gridLayout_5.addWidget(self.label_4, 0, 0, 1, 2)
        self.spinBoxId = QtWidgets.QSpinBox(self.tabCreate)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBoxId.sizePolicy().hasHeightForWidth())
        self.spinBoxId.setSizePolicy(sizePolicy)
        self.spinBoxId.setMinimumSize(QtCore.QSize(121, 22))
        self.spinBoxId.setMaximumSize(QtCore.QSize(150, 22))
        self.spinBoxId.setStyleSheet("\n"
"  border: 2px solid #ccc;\n"
"  border-radius: 4px;\n"
"  background-color: #f8f8f8;")
        self.spinBoxId.setWrapping(False)
        self.spinBoxId.setSpecialValueText("")
        self.spinBoxId.setAccelerated(True)
        self.spinBoxId.setProperty("showGroupSeparator", True)
        self.spinBoxId.setMinimum(1)
        self.spinBoxId.setMaximum(7000)
        self.spinBoxId.setObjectName("spinBoxId")
        self.gridLayout_5.addWidget(self.spinBoxId, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tabCreate, "")
        self.tabList = QtWidgets.QWidget()
        self.tabList.setObjectName("tabList")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.tabList)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.pushButtonListPartners = QtWidgets.QPushButton(self.tabList)
        self.pushButtonListPartners.setObjectName("pushButtonListPartners")
        self.gridLayout_7.addWidget(self.pushButtonListPartners, 1, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem4, 1, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem5, 1, 4, 1, 1)
        self.pushButtonClear = QtWidgets.QPushButton(self.tabList)
        self.pushButtonClear.setObjectName("pushButtonClear")
        self.gridLayout_7.addWidget(self.pushButtonClear, 1, 3, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(self.tabList)
        self.tableWidget.setStyleSheet("\n"
"  border: 2px solid #ccc;\n"
"  border-radius: 4px;\n"
"  background-color: #f8f8f8;")
        self.tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(8)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        self.tableWidget.verticalHeader().setVisible(False)
        self.gridLayout_7.addWidget(self.tableWidget, 0, 0, 1, 5)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem6, 1, 2, 1, 1)
        self.tabWidget.addTab(self.tabList, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.statusBar.setFont(font)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Ze-Code-Challenge"))
        self.groupBox.setTitle(_translate("MainWindow", "Get Partner by ID"))
        self.label.setText(_translate("MainWindow", "ID Partner"))
        self.lineEditIdPartner.setPlaceholderText(_translate("MainWindow", "int"))
        self.pushButtonSearchById.setText(_translate("MainWindow", "Serach by ID"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Search Partner by Coordinates"))
        self.pushButtonSearchByCoordinates.setText(_translate("MainWindow", "Search by coodinates"))
        self.label_2.setText(_translate("MainWindow", "Latitude"))
        self.lineEditLatitude.setPlaceholderText(_translate("MainWindow", "Float 12.345..."))
        self.label_3.setText(_translate("MainWindow", "Longitude"))
        self.lineEditLongitude.setPlaceholderText(_translate("MainWindow", "Float 12.345"))
        self.label_11.setText(_translate("MainWindow", "Result Search"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabHome), _translate("MainWindow", "Home"))
        self.label_5.setText(_translate("MainWindow", "Trading Name"))
        self.lineEditTradingName.setPlaceholderText(_translate("MainWindow", "String"))
        self.label_6.setText(_translate("MainWindow", "Owner Name"))
        self.lineEditOwnerName.setPlaceholderText(_translate("MainWindow", "String"))
        self.label_7.setText(_translate("MainWindow", "Document"))
        self.lineEditDocument.setPlaceholderText(_translate("MainWindow", "String"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Coverage Area"))
        self.label_8.setText(_translate("MainWindow", "Coordinates"))
        self.textEditCoverageArea.setPlaceholderText(_translate("MainWindow", "EX : [ ( , ), ( , ), ( , ), ( , ) ], [ ( , ), ( , ), ( , ), ( , ) ]"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Address"))
        self.label_9.setText(_translate("MainWindow", "Latitude"))
        self.lineEditLatitude_2.setPlaceholderText(_translate("MainWindow", "Float 12.3456..."))
        self.label_10.setText(_translate("MainWindow", "Longitude"))
        self.lineEditLongitude_2.setPlaceholderText(_translate("MainWindow", "Float -12.3456..."))
        self.pushButtonSaveEntry.setText(_translate("MainWindow", "Save Entry"))
        self.label_4.setText(_translate("MainWindow", "ID"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabCreate), _translate("MainWindow", "Create Partner"))
        self.pushButtonListPartners.setText(_translate("MainWindow", "List all Partners"))
        self.pushButtonClear.setText(_translate("MainWindow", "Clear"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Trading Name"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Owner Name"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "CNPJ"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Cover Area Type"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Cover Area Coord"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Address Type"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Address Coord"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabList), _translate("MainWindow", "List Partners"))


from PyQt5 import QtWebEngineWidgets
